project:
  title: "Markdown"
  output-dir: docs

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    html-math-method: katex
    self-contained: true
    code-fold: true
    code-overflow: wrap
    code-summary: Show the code
    code-block-border-left: "#31BAE9"
    citations-hover: true
    footnotes-hover: true
    link-external-icon: true
  revealjs:
    self-contained: false
    code-fold: false
    code-overflow: wrap
    footer: "[Dyerlab](https://dyerlab.org)"
    code-block-border-left: "#31BAE9"
  


